import type { Metadata } from "next";
import "./globals.css";
import { Geist } from "next/font/google";
import { cn } from "@/shared/lib/utils";
import { Navbar } from "@/widgets/navbar/index"; 
import { Footer } from "@/widgets/footer/index";
import { ReactToast } from "@/providers";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en" className={`
        bg-[url('/PAWS_final.png')] 
        bg-repeat-y
        bg-[length:100%_auto]
        min-h-screen
        ${cn("font-sans", geist.variable)}
      `}
    >
      <Navbar/>
      <body className="min-h-full flex flex-col">
        {children}
        <ReactToast/>
      </body>
      <Footer/>
    </html>
  );
}