services:
  - name: go-service
    type: web
    runtime: image
    repo: https://github.com/Agile-201/petSwipe
    context: backend/Go-service
    dockerfilePath: Dockerfile.api
    plan: free
    envVars:
      - key: API_ADDRESS
        value: :8080
      - key: LOG_LEVEL
        value: DEBUG
      - key: TOKEN_TTL
        value: 24h
      - key: POSTGRES_HOST
        fromDatabase:
          name: pet-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: pet-db
          property: port
      - key: POSTGRES_USER
        fromDatabase:
          name: pet-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: pet-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: pet-db
          property: database
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /health
    numReplicas: 1

  - name: cpp-service
    type: web
    runtime: image
    repo: https://github.com/Agile-201/petSwipe
    context: backend/C-service
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: POSTGRES_HOST
        fromDatabase:
          name: pet-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: pet-db
          property: port
      - key: POSTGRES_USER
        fromDatabase:
          name: pet-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: pet-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: pet-db
          property: database
      - key: JWT_SECRET
        sync: false
    # временно убираем healthCheck, если у C++ сервиса нет /health
    # healthCheckPath: /health
    numReplicas: 1

  - name: nginx
    type: web
    runtime: image
    repo: https://github.com/Agile-201/petSwipe
    context: backend
    dockerfilePath: nginx.Dockerfile
    plan: free
    envVars: []
    healthCheckPath: /health
    numReplicas: 1

databases:
  - name: pet-db
    databaseName: petswipe
    plan: free
    ipAllowList: []