upstream go_backend {
    server go_service:8080;
}

upstream cpp_backend {
    server cpp_service:8081;
}

server {
    listen 80;
    server_name _;

    client_max_body_size 100M;

    # Health check
    location /health {
        access_log off;
        return 200 "Gateway OK\n";
        add_header Content-Type application/json;
    }

    # Аутентификация и работа с пользователями
    location /api/auth/ {
        proxy_pass http://go_backend/api/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        proxy_http_version 1.1;
    }

    # Чат
    location /api/chat/ {
        proxy_pass http://go_backend/api/chat/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        proxy_http_version 1.1;
    }

    # Профиль пользователя
    location /api/users/ {
        proxy_pass http://go_backend/api/users/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        proxy_http_version 1.1;
    }

    # Пинг для проверки жизни Go сервиса
    location /api/ping {
        proxy_pass http://go_backend/api/ping;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 404 для неизвестных маршрутов
    location / {
        return 404;
    }

    # Отключает логирование для robots.txt
    location = /robots.txt {
        access_log off;
        return 404;
    }

    # Отключает логирование для favicon.ico
    location = /favicon.ico {
        access_log off;
        return 404;
    }
}
